const http2 = require('http2');

const {
  HTTP_STATUS_BAD_REQUEST: BAD_REQUEST_400,
  HTTP_STATUS_UNAUTHORIZED: UNAUTHORIZED_401,
  HTTP_STATUS_NOT_FOUND: NOT_FOUND_404,
  HTTP_STATUS_INTERNAL_SERVER_ERROR: INTERNAL_SERVER_ERROR_500,
} = http2.constants;

module.exports = {
  BAD_REQUEST_400,
  UNAUTHORIZED_401,
  NOT_FOUND_404,
  INTERNAL_SERVER_ERROR_500,
};
